# Generated by Django 5.2.4 on 2025-08-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_author_books_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
