# Generated by Django 5.2.4 on 2025-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
