# Generated by Django 5.2.4 on 2025-08-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
