# Generated by Django 5.2.5 on 2025-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_backgrounds/'),
        ),
    ]
