# Generated by Django 5.2.4 on 2025-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_email_remove_game_username_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to='games/'),
            preserve_default=False,
        ),
    ]
