# Generated by Django 5.2.4 on 2025-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_link',
            field=models.URLField(blank=True),
        ),
    ]
