# Generated by Django 5.2.4 on 2025-08-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='message',
            new_name='details',
        ),
    ]
