# Generated by Django 5.2.5 on 2025-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_authors_country_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
