# Generated by Django 5.2.5 on 2025-08-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_planet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planet',
            new_name='Continent',
        ),
    ]
