# Generated by Django 5.2.5 on 2025-08-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_planet_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.continent'),
        ),
    ]
