# Generated by Django 5.2.5 on 2025-08-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_country_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AlterField(
            model_name='authors',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book.country'),
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
