# Generated by Django 5.2.4 on 2025-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Image/')),
                ('details', models.TextField()),
                ('generation', models.TextField()),
                ('ram', models.PositiveIntegerField(help_text='RAM in GB')),
                ('ssd', models.PositiveIntegerField(help_text='SSD in GB')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
